### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-accounting#116]
We need a simple profile page with a login, forgotten password thingy and password change option since the only way to change the password currently is with the android app, which just happens to crash when trying to do that.

At least the released version does that.

**Comment by enkore** [comment]
t-note: resolved via [password reset](https://accounting.qabel.org/accounts/password_reset/) function which, while ugly, gets the job done. milestone = probably after rc / low prio.

**Comment by thechauffeur** [comment]
@audax does the password reset function in Android still crash?

**Comment by thechauffeur** [comment]
Aside from my question above this is definitely after RC.

**Comment by enkore** [comment]
Technically already implemented, but currently disabled functionality, since text/UI has not been reviewed yet.
